# Generated by Django 3.1 on 2020-08-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproject',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='faq_icon',
            field=models.ImageField(default='', upload_to='images', verbose_name='Faq icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='key_words',
            field=models.CharField(default='', max_length=500, verbose_name='Key words'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='logo',
            field=models.ImageField(default='', upload_to='images', verbose_name='Logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='title',
            field=models.CharField(default='', max_length=60, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='cover_image',
            field=models.ImageField(default='', upload_to='image', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
